### ISSUE TITLE
加一个股票的当日跌涨幅吧，然后实时刷新。当前和开盘价格，不好计算/ 苦笑

### ISSUE THREAD

**Issue by y1324** [dengzii/FundAssistant#10]
加一个股票的当日跌涨幅吧，然后实时刷新。当前和开盘价格，不好计算/ 苦笑

**Comment by y1324** [comment]
本来想看看怎么写的，一看java这就尴尬了，不会。

**Comment by dengzii** [comment]
实时刷新有，默认几十秒刷新一次， 跌幅后面考虑加 👌
Kotlin + Java 结合的
