### ISSUE TITLE
基金无法打开编辑窗口

### ISSUE THREAD

**Issue by Kerwin-Ma** [dengzii/FundAssistant#11]
股票可以正常添加，但是基金的编辑按钮无法打开窗口，没办法添加基金。

**Comment by dengzii** [comment]
我这无法复现

**Comment by Kerwin-Ma** [comment]
我是在 IDEA的插件里面搜索安装的，和这有关系吗？

**Comment by dengzii** [comment]
没有啊, 我也是搜索安装的

**Comment by Kerwin-Ma** [comment]
> 没有啊, 我也是搜索安装的

那可能是我IDEA版本的问题了，或者是其他问题。2020.2的IDEA
