### ISSUE TITLE
安装后添加基金不弹窗，但是在股票标签页添加股票是可以弹窗的

### ISSUE THREAD

**Issue by sunl888** [dengzii/FundAssistant#12]
idea版本：IntelliJ IDEA 2021.1.2 (Ultimate Edition)
Build #IU-211.7442.40, built on June 1, 2021
Licensed to IntelliJ IDEA Evaluator
Expiration date: July 24, 2021
Runtime version: 11.0.11+9-b1341.57 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8
Non-Bundled Plugins: ArthasHotSwap (1.3-since-2020.3.3-RELEASE), com.huage2580.leeks (1.9.1), com.jetbrains.nim (1.4.0-203), com.jetbrains.plugins.ini4idea (211.6693.44), commit-template-idea-plugin (1.2.0), io.github.biezhi.plugins.gitmoji (1.0.2), io.zhile.research.ide-eval-resetter (2.1.14), mobi.hsz.idea.gitignore (4.1.0), GrepConsole (11.10.211.6086.0), GsonFormatPlus (1.6.1), com.github.wangji92.arthas.plugin (2.31), com.github.leecho.idea.plugin.mybatis.generator (1.5), MavenRunHelper (4.13.203.000.0), org.jetbrains.kotlin (211-1.5.20-release-284-IJ7442.40), com.ccnode.codegenerator.MyBatisCodeHelperPro (2.9.3-183-204), com.bruce.intellijplugin.generatesetter (2.7), izhangzhihao.rainbow.brackets (6.18), ru.adelf.idea.dotenv (2021.2), com.itangcent.idea.plugin.easy-yapi (2.2.3.183.0-rc), com.dengzii.plugin.fund (1.1.0)
Kotlin: 211-1.5.20-release-284-IJ7442.40

**Comment by dengzii** [comment]
从来没弹出来过吗

**Comment by sunl888** [comment]
> 从来没弹出来过吗

是的，但是在股票页面可以弹出来

**Comment by dengzii** [comment]
可能是网络问题, 首次打开 添加基金 会发出一个获取所有基金信息的请求

**Comment by dengzii** [comment]
试试这个链接能不能打开  
http://fund.eastmoney.com/js/fundcode_search.js

**Comment by sunl888** [comment]
> 可能是网络问题, 首次打开 添加基金 会发出一个获取所有基金信息的请求

有相关的日志吗？我想查一下日志

**Comment by sunl888** [comment]
> 试试这个链接能不能打开
> http://fund.eastmoney.com/js/fundcode_search.js

可以的，打开很快

**Comment by dengzii** [comment]
日志木得, 那可能代码出错了,

**Comment by sunl888** [comment]
> 日志木得, 那可能代码出错了,

对应的弹窗代码在哪里可以 引用一下吗？我准备fork下来简单调试一下，但是kt代码我不太了解 ^^

**Comment by dengzii** [comment]
打开编辑基金窗口  

https://github.com/dengzii/FundAssistant/blob/f002358d6541a470365d8228461b9ddf250971df/src/com/dengzii/plugin/fund/ui/fund/FundPanel.kt#L59

编辑基金窗口

https://github.com/dengzii/FundAssistant/blob/f002358d6541a470365d8228461b9ddf250971df/src/com/dengzii/plugin/fund/ui/fund/EditFundGroupListDialog.kt#L39

天天基金 API

https://github.com/dengzii/FundAssistant/blob/f002358d6541a470365d8228461b9ddf250971df/src/com/dengzii/plugin/fund/api/TianTianFundApi.java#L23

**Comment by sunl888** [comment]
> 打开编辑基金窗口
> 
> https://github.com/dengzii/FundAssistant/blob/f002358d6541a470365d8228461b9ddf250971df/src/com/dengzii/plugin/fund/ui/fund/FundPanel.kt#L59
> 
> 编辑基金窗口
> 
> https://github.com/dengzii/FundAssistant/blob/f002358d6541a470365d8228461b9ddf250971df/src/com/dengzii/plugin/fund/ui/fund/EditFundGroupListDialog.kt#L39
> 
> 天天基金 API
> 
> https://github.com/dengzii/FundAssistant/blob/f002358d6541a470365d8228461b9ddf250971df/src/com/dengzii/plugin/fund/api/TianTianFundApi.java#L23

Thanks.

**Comment by dengzii** [comment]
调试项目参考这个 👍

https://github.com/dengzii/GenerateModuleFromTemplate#build

**Comment by sunl888** [comment]
> 调试项目参考这个 👍
> 
> https://github.com/dengzii/GenerateModuleFromTemplate#build

ok，这个文章帮了我大忙
