### ISSUE TITLE
android studio 安装后，点击编辑无效

### ISSUE THREAD

**Issue by AlphaXu917** [dengzii/FundAssistant#13]
Android Studio Arctic Fox | 2020.3.1 Patch 3
Build #AI-203.7717.56.2031.7784292, built on October 1, 2021
android studio 安装后，点击编辑无效，没有反应

**Comment by dengzii** [comment]
可能是请求没有成功, 第一次点编辑的时候会先获取一下所有基金列表, 没有返回数据就可能是没成功, 多试几次应该可以

**Comment by AlphaXu917** [comment]
尝试多次无果，股票是正常的！基金不行



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月6日(周一) 上午10:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [dengzii/FundAssistant] android studio 安装后，点击编辑无效 (Issue #13)




 
可能是请求没有成功, 第一次点编辑的时候会先获取一下所有基金列表, 没有返回数据就可能是没成功, 多试几次应该可以
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dengzii** [comment]
我尝试修复一下, 感谢提交问题

**Comment by MentosL** [comment]
IntelliJ IDEA 2021.3 (Ultimate Edition)
Runtime version: 11.0.13+7-b1751.19 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.0.1
Non-Bundled Plugins:
    com.dengzii.plugin.fund (1.1.1)


同样编辑无响应  @dengzii

**Comment by dengzii** [comment]
@MentosL http://fund.eastmoney.com/js/fundcode_search.js 这个连接能打开吗

**Comment by MentosL** [comment]
> @MentosL http://fund.eastmoney.com/js/fundcode_search.js 这个连接能打开吗

可以
目前在idea中 点击编辑无变化

**Comment by dengzii** [comment]
收到, 我现在就试着修复一下

**Comment by MentosL** [comment]
股票编辑正常   目前就是基金点击无响应

**Comment by AlphaXu917** [comment]
> 

一样的问题，提出来至今还没解决呢

**Comment by dengzii** [comment]
@JsonDing 😂 太忙了, 我这一直没复现, 无从下手

**Comment by AlphaXu917** [comment]
> 可能是请求没有成功, 第一次点编辑的时候会先获取一下所有基金列表, 没有返回数据就可能是没成功, 多试几次应该可以

为何要一开始获取所有的基金列表啊，使用者添加哪个显示哪个，未添加，显示所有的没啥大意义

**Comment by AlphaXu917** [comment]
> @JsonDing 😂 太忙了, 我这一直没复现, 无从下手

理解

**Comment by dengzii** [comment]
@JsonDing 主要是只有一个接口, 只能一次性获取全部的数据, 木得办法

**Comment by dengzii** [comment]
好了, 也不知道行不行, 插件市场两个工作日内审核更新, 手动更新在这 -> [Release V1.2.1](https://github.com/dengzii/FundAssistant/releases/tag/v1.2.1)

**Comment by AlphaXu917** [comment]
好的👌🏻



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月14日(周二) 上午10:31
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [dengzii/FundAssistant] android studio 安装后，点击编辑无效 (Issue #13)




 
收到, 我现在就试着修复一下
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MentosL** [comment]
> 好了, 也不知道行不行, 插件市场两个工作日内审核更新, 手动更新在这 -> [Release V1.2.1](https://github.com/dengzii/FundAssistant/releases/tag/v1.2.1)

可以了  辛苦大佬

**Comment by MentosL** [comment]
> 好了, 也不知道行不行, 插件市场两个工作日内审核更新, 手动更新在这 -> [Release V1.2.1](https://github.com/dengzii/FundAssistant/releases/tag/v1.2.1)

产生一个新的问题，编辑基金的时候，首先输入找到第一个基金，清空准备输入第二个的时候就卡主了。导致idea无响应

**Comment by dengzii** [comment]
@MentosL 我这个搜索就是遍历, 我优化一下
