### ISSUE TITLE
Stock

### ISSUE THREAD

**Issue by 123114** [dengzii/FundAssistant#6]
什么时候能支持股票呀

**Comment by dengzii** [comment]
🤣 下一个版本就支持

**Comment by 123114** [comment]
最近一次更新 都5天了呀，绿的我发慌，急不可耐啊

**Comment by dengzii** [comment]
🤣 别急哈, 我空闲就开发, 今天就写点
坚持住, 我做好了被套一年的准备

**Comment by 123114** [comment]
不可能被套，天天得做T，加油啊，不然没法一直关注趋势，难受

**Comment by dengzii** [comment]
稳住, 心态要好

**Comment by dengzii** [comment]
[v1.1.0](https://github.com/dengzii/FundAssistant/releases/tag/v1.1.0) 支持股票了, 插件市场在审核中, release 已发布

**Comment by 123114** [comment]
大佬 牛逼

**Comment by 123114** [comment]
基金的 红色颜色不好看，眼要瞎了， 股票不显示名称，是时间没到吗

**Comment by dengzii** [comment]
我这试了没问题诶, 所有字段都可以显示, 可以改成白色, 细节下个版本更新
